# Generated by Django 5.2.14 on 2026-06-01 21:04

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('isbn', models.CharField(max_length=20)),
                ('isbn_normalized', models.CharField(max_length=13, unique=True)),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('published_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title'], name='book_title_trgm_idx', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['author'], name='book_author_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
