# Generated by Django 5.2.14 on 2026-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
